export { default as tLFS} from '../objects/tallLightFlatSquare.glb';
export { default as tLHC} from '../objects/tallLightHoleCylinder.glb';
export { default as pieceThatGoesInHole} from '../objects/pieceThatGoesInHole.glb';
export { default as floor} from '../objects/floor.glb';
export { default as slab} from '../objects/slabForPieces.glb';
export { default as sDFC} from '../objects/shortDarkFlatCylinder.glb';
export { default as sDFS} from '../objects/shortDarkFlatSquare.glb';
export { default as sDHC} from '../objects/shortDarkHoleCylinder.glb';
export { default as sDHS } from '../objects/shortDarkHoleSquare.glb';
export { default as sLFC } from '../objects/shortLightFlatCylinder.glb';
export { default as sLFS } from '../objects/shortLightFlatSquare.glb';
export { default as sLHC } from '../objects/shortLightHoleCylinder.glb';
export { default as sLHS } from '../objects/shortLightHoleSquare.glb';
export { default as tDFC } from '../objects/tallDarkFlatCylinder.glb';
export { default as tDFS } from '../objects/tallDarkFlatSquare.glb';
export { default as tDHC } from '../objects/tallDarkHoleCylinder.glb';
export { default as tDHS } from '../objects/tallDarkHoleSquare.glb';
export { default as tLFC } from '../objects/tallLightFlatCylinder.glb';
export { default as tLHS } from '../objects/tallLightHoleSquare.glb';
export { default as gameBoard } from '../objects/gameBoard.glb';
export { default as coaster } from '../objects/coaster.glb';